import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import Response from '../components/Response'

export default function Home() {

  const [prompt, setPrompt] = useState('')
  const [response, setResponse] = useState('')

  const handleTextChange = (event) => {
    // console.log(event.target.value)
    setPrompt(event.target.value)
    console.log(prompt)
  }

  const handleGenerate = () => {
    console.log('here is what we\'ll be passing:', prompt)
    // hit he OPEN AI API?
    // then render the response below
    // use setResponse 
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to The Time Traveler
        </h1>

        <div>
          <span>Learn about any period or any person in history</span>
        </div>

        <div className="prompt-container">
          <textarea value={prompt} name="prompt" id="prompt" cols="40" rows="10" placeholder='What part of history do you want to learn about?' onChange={handleTextChange}></textarea>
        </div>

        <div className="generate-button-div">
          <button className="genereate-button" onClick={handleGenerate}>Generate!</button>
        </div>

        <div className="response-container">
          <br /><br />
          <span className="response-span">Response below</span>
          {/* if response state is not empty string, render Response component? */}
          <Response />
        </div>

        
      </main>

      <footer className={styles.footer}>
        <span>Powered by GPT-3 and the human brain of <a href="https://parkersteinberg.com/"  target="_blank" rel="noreferrer">Parker Steinberg</a></span>
      </footer>
    </div>
  )
}
